### ISSUE TITLE
[질문] 어디서 수업 신청을 할 수 있을까요?

### ISSUE THREAD

**Issue by erinyees** [hatemogi/html.coffee#1]
'n회차'형태로 정기적인 교육을 진행하시는듯한데 외부 신청 링크가 있을까요?

**Comment by hatemogi** [comment]
관심 감사드립니다. 현재 사내에서 디자이너&기획자 대상으로 스터디 진행 중입니다. 스터디 참가자분들 보시라고 공개리포로 열어둔 상태입니다. 외부는 아직 계획이 없는 단계인데요, 혹시 추가 자료가 있으면 여기에 공유하겠습니다.

**Comment by erinyees** [comment]
넵, 감사합니다.
